trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml
      - README.md
      - docs/**

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2

variables:
  pythonVersion: '3.11'

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(pythonVersion)'
#     addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest
  displayName: 'Run tests'
