trigger:
  branches:
    include:
      - main

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2  # Make sure this matches your agent capabilities

variables:
  python_version: '3.11'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Build
    displayName: 'Run Tests on Self-hosted Agent'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python_version)'
        addToPath: true

    - script: |
        python -m venv venv
        call venv\Scripts\activate.bat
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
      displayName: 'Create venv and install dependencies'

    - script: |
        call venv\Scripts\activate.bat
        pytest
      displayName: 'Run tests'
      continueOnError: false