trigger:
  branches:
    include:
      - main

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2

variables:
  python_version: '3.11'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Build
    displayName: 'Install Python and Run Tests'
    steps:
    
    - powershell: |
        Write-Host "Installing Chocolatey if not present..."
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }

        Write-Host "Installing Python $(python_version)..."
        choco install python --version=$(python_version) -y --force

        $pythonPath = (Get-Command python).Path
        Write-Host "Python installed at: $pythonPath"
      displayName: 'Install Python via Chocolatey'

    - powershell: |
        python --version
        python -m venv venv
        .\venv\Scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - powershell: |
        .\venv\Scripts\activate
        pytest
      displayName: 'Run tests'
      continueOnError: false