trigger:
  branches:
    include:
      - main

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2

variables:
  python_version: '3.11.9'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Build
    displayName: 'Install Python & Run Tests'
    steps:

    - powershell: |
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/$(python_version)/python-$(python_version)-amd64.exe" -OutFile "python-installer.exe"
        Start-Process -FilePath "python-installer.exe" -ArgumentList '/quiet InstallAllUsers=0 PrependPath=1 Include_test=0' -Wait
        python --version
      displayName: 'Install Python locally (no registry access)'

    - script: |
        python -m venv venv
        venv\Scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        venv\Scripts\activate
        pytest
      displayName: 'Run tests'
      continueOnError: false