trigger:
  branches:
    include:
      - main

pool:
  name: MyFreePool
  demands:
    - agent -equals agent2

variables:
  python_version: '3.11'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python_version)'
        addToPath: true

    - script: |
        python -m venv venv
        venv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        venv\Scripts\activate
        pytest
      displayName: 'Run tests'
