trigger:
  branches:
    include:
      - main

pool:
  name: MyFreePool
  demands:
    - agent.name -equals agent2  # ✅ Use correct demand syntax

variables:
  python_version: '3.11'
  venv_dir: 'venv'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: Build
    displayName: 'Run Tests on Self-hosted Agent'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python_version)'
        addToPath: true

    - script: |
        python -m venv $(venv_dir)
        call $(venv_dir)\Scripts\activate.bat
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies (Windows)'

    - script: |
        call $(venv_dir)\Scripts\activate.bat
        pytest --junitxml=test-results.xml
      displayName: 'Run tests'
      continueOnError: false  # ❗ Fails pipeline if tests fail

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-results.xml'
        testRunTitle: 'Python Test Results'
